package com.cwc.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setOpenid(String openid) {
		set("openid", openid);
	}

	public String getOpenid() {
		return getStr("openid");
	}

	public void setSessionKey(String sessionKey) {
		set("session_key", sessionKey);
	}

	public String getSessionKey() {
		return getStr("session_key");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return getStr("token");
	}

}
